export {
	AI_INSTRUCTIONS,
	SOLVE_AND_ANSWER_INSTRUCTION,
	WRITE_CODE_INSTRUCTION,
	EXTRACT_CSS_INSTRUCTION,
	RECOGNIZE_CONTENT_INSTRUCTION,
	CONVERT_DATA_INSTRUCTION,
	EXTRACT_ENTITIES_INSTRUCTION,
	TRANSLATE_TO_LANGUAGE_INSTRUCTION,
	GENERAL_PROCESSING_INSTRUCTION,
	CRX_SOLVE_AND_ANSWER_INSTRUCTION,
	CRX_WRITE_CODE_INSTRUCTION,
	CRX_EXTRACT_CSS_INSTRUCTION,
	EQUATION_SOLVE_INSTRUCTION,
	ANSWER_QUESTION_INSTRUCTION,
	IMAGE_INSTRUCTION,
	DATA_CONVERSION_INSTRUCTION,
	ENTITY_EXTRACTION_INSTRUCTION,
	DATA_MODIFICATION_INSTRUCTION,
} from "../service/instructions/core";

export {
	DEFAULT_TEMPLATES,
	BUILT_IN_AI_ACTIONS,
	DEFAULT_INSTRUCTION_TEMPLATES,
	type BuiltInAIAction,
} from "../service/instructions/templates";

export {
	buildInstructionPrompt,
	SVG_GRAPHICS_ADDON,
	generateInstructionId,
	type CustomInstruction,
} from "../service/instructions/utils";
